import Link from "next/link";
import Head from "next/head";
import { Navbar } from "../widgets/Navbar";

const about = () => {
  return (
    <>
      <Head>
        <title>Quiénes somos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-yellow-100 pb-6 md:pb-10"></div>
    </>
  );
};

export default about;
