import Link from "next/link";
import Head from "next/head";
import { Navbar } from "../widgets/Navbar";

const about = () => {
  return (
    <>
      <Head>
        <title>Quiénes somos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default about;
