import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>Quiénes somos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-yellow-100 pb-6 md:pb-10">
        <section className="px-6 mx-auto pt-20 md:max-w-screen-md lg:max-w-screen-lg xl:max-w-screen-xl">
          <h2 className="text-2xl sm:text-3xl lg:text-4xl font-semibold text-yellow-600 py-3">
            ¿Qué es Bee Happy?
          </h2>
          <p className="text-base sm:text-lg text-gray-700 font-medium mb-6">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit.
            Necessitatibus, excepturi minima! Distinctio, repellendus?
            Voluptatum blanditiis itaque commodi consectetur laborum minima
            omnis repellat deleniti, vitae vero beatae impedit facere veniam
            numquam facilis voluptas labore? Facilis ducimus distinctio incidunt
            assumenda eaque! Quis nemo error eveniet magni enim odit nesciunt
            doloremque ad amet.
          </p>
          <p className="text-base sm:text-lg text-gray-700 font-medium mb-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium
            facilis temporibus, repellat necessitatibus recusandae at non
            tempora quam dignissimos. Aperiam!
          </p>
          <h2 className="text-2xl sm:text-3xl lg:text-4xl font-semibold text-yellow-600 py-3">
            Misión
          </h2>
          <p className="text-base sm:text-lg text-gray-700 font-medium mb-6">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit.
            Necessitatibus, excepturi minima! Distinctio, repellendus?
            Voluptatum blanditiis itaque commodi consectetur laborum minima
            omnis repellat deleniti, vitae vero beatae impedit facere veniam
            numquam facilis voluptas labore? Facilis ducimus distinctio incidunt
            assumenda eaque! Quis nemo error eveniet magni enim odit nesciunt
            doloremque ad amet.
          </p>
          <h2 className="text-2xl sm:text-3xl lg:text-4xl font-semibold text-yellow-600 py-3">
            Visión
          </h2>
          <p className="text-base sm:text-lg text-gray-700 font-medium mb-6">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit.
            Necessitatibus, excepturi minima! Distinctio, repellendus?
            Voluptatum blanditiis itaque commodi consectetur laborum minima
            omnis repellat deleniti, vitae vero beatae impedit facere veniam
            numquam facilis voluptas labore? Facilis ducimus distinctio incidunt
            assumenda eaque! Quis nemo error eveniet magni enim odit nesciunt
            doloremque ad amet.
          </p>
        </section>
      </div>
    </>
  );
};

export default about;
