import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import { Navbar } from "@widgets/Navbar";
import { Disclosure } from "@headlessui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bee Happy</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="bg-yellow-500">
        <Disclosure>
          <Disclosure.Button className="py-2">
            Is team pricing available?
          </Disclosure.Button>
          <Disclosure.Panel className="text-gray-500">
            Yes! You can purchase a license that you can share with your entire
            team.
          </Disclosure.Panel>
        </Disclosure>

        <h1 className="text-xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
        <h1 className="text-9xl">Hola</h1>
      </div>
    </>
  );
};

export default Home;
